employee_name = input("Enter employee name: ")
employee_id = input("Enter employee ID: ")
gross_monthly_salary = float(input("Enter gross monthly salary: "))
annual_gross_salary = float(input("Enter annual gross salary: "))
taxable_income = float(input("Enter taxable income: "))
tax_payable = float(input("Enter tax payable: "))
annual_net_salary = float(input("Enter annual net salary: "))

print("\nEmployee Tax Report")
print("+----------------------+----------------------+")
print("| Field                | Details              |")
print("+----------------------+----------------------+")
print(f"| Name                 | {employee_name:<20} |")
print(f"| EmpID                | {employee_id:<20} |")
print(f"| Gross Monthly Salary | ₹{gross_monthly_salary:,.0f}           |")
print("+----------------------+----------------------+")
print(f"| Annual Gross Salary  | ₹{annual_gross_salary:,.0f}           |")
print(f"| Taxable Income       | ₹{taxable_income:,.0f}           |")
print(f"| Tax Payable          | ₹{tax_payable:,.0f}           |")
print(f"| Annual Net Salary    | ₹{annual_net_salary:,.0f}           |")
print("+----------------------+----------------------+")
